### ISSUE TITLE
Sodexo mudou a forma de consulta

### ISSUE THREAD

**Issue by micaelsouza** [sodexounofficial/sodexo#2]

**Comment by pereirajair** [comment]
Olá, vi que você criou 2 variáveis de ambiente, que são a chave de criptografia e o algoritimo... sem elas acredito que fica impossível fazer o código funcionar. Também entendo os motivos de não publicar elas aqui, mas como você conseguiu essas chaves? Obrigado.

**Comment by micaelsouza** [comment]
Então, @pereirajair, consegui essa chave fuçando códigos pelo GitHub. Por motivos que você entende, eu não posso publicar ela aqui e nem ficar repassando. Caso você precise fazer uso da API do sodexo, pode usar a API não oficial que eu hospedei no heroku.

```
POST /api/saldo HTTP/1.1
Host: sodexo.herokuapp.com
Content-Type: application/x-www-form-urlencoded

card=0000000000000000&document=00000000000
```

**Comment by m98proxy** [comment]
@pereirajair se ainda precisa me chama em privado, abs.
