### ISSUE TITLE
https://www.app.sodexo.com.br/PMobileServer/Primeth

### ISSUE THREAD

**Issue by iancesar** [sodexounofficial/sodexo#4]
Micael, realizei a implementação usando as chaves que me foram passadas por e-mail, porém estou recebendo o erro 
https://www.app.sodexo.com.br/PMobileServer/Primeth net::ERR_CONNECTION_RESET

![image](https://user-images.githubusercontent.com/5034007/68811478-80203980-064f-11ea-8268-ad2a1772bd6f.png)

**Comment by micaelsouza** [comment]
@iancesar, eu analisei o problema e descobri que eles descontinuaram esse endpoint e o app que eu inspecionei pra descobrir esse endpoint também não está mais disponível. Pelo que eu vi, eles criaram um novo app e esse precisa de login e senha pra consultar o saldo dos cartões. Eu já não uso mais os cartões da sodexo onde eu trabalho então, não vai dá pra tentar inspecionar o novo app pra descobrir como ele consulta o saldo. Eu vou atualizar o README do repositório pra informar que ele já não funciona mais.
